
package com.example.imdb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Imdb", targetNamespace = "http://www.example.com/imdb", wsdlLocation = "http://localhost:8080/ImdbSOAPWebService/Imdb.wsdl")
public class Imdb
    extends Service
{

    private final static URL IMDB_WSDL_LOCATION;
    private final static WebServiceException IMDB_EXCEPTION;
    private final static QName IMDB_QNAME = new QName("http://www.example.com/imdb", "Imdb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ImdbSOAPWebService/Imdb.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMDB_WSDL_LOCATION = url;
        IMDB_EXCEPTION = e;
    }

    public Imdb() {
        super(__getWsdlLocation(), IMDB_QNAME);
    }

    public Imdb(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMDB_QNAME, features);
    }

    public Imdb(URL wsdlLocation) {
        super(wsdlLocation, IMDB_QNAME);
    }

    public Imdb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMDB_QNAME, features);
    }

    public Imdb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Imdb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImdbSoapService
     */
    @WebEndpoint(name = "ImdbSoapServicePort")
    public ImdbSoapService getImdbSoapServicePort() {
        return super.getPort(new QName("http://www.example.com/imdb", "ImdbSoapServicePort"), ImdbSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImdbSoapService
     */
    @WebEndpoint(name = "ImdbSoapServicePort")
    public ImdbSoapService getImdbSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/imdb", "ImdbSoapServicePort"), ImdbSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMDB_EXCEPTION!= null) {
            throw IMDB_EXCEPTION;
        }
        return IMDB_WSDL_LOCATION;
    }

}
