
package com.example.imdb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImdbSoapService", targetNamespace = "http://www.example.com/imdb")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImdbSoapService {


    /**
     * 
     * @param criteria
     * @return
     *     returns java.util.List<com.example.imdb.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://www.example.com/imdb", className = "com.example.imdb.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://www.example.com/imdb", className = "com.example.imdb.SearchResponse")
    public List<Movie> search(
        @WebParam(name = "criteria", targetNamespace = "")
        CriteriaBean criteria);

}
