//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 10:15:20 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deepcloudlabs.com/2020/otomobiller", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.deepcloudlabs._2020.otomobiller;
